# All GPG keys must be full fingerprints, not 8-digit.
#
# Make sure the inventory_hostname here is able to be looked up with DNS for
# firewall purposes and is a A record so that we return a IP address. Also
# make sure that dig command is install on controller.
#

localhost ansible_connection=local

[backup_primary]
mymainserver.example.com gpg_keyid=FIXME1 gpg_passphrase=FIXME2

[backup_secondary]
mysecondaryserver.example.com

[backup_clients]
# backup_include and backup_exclude will overwrite the default set
# If you want to change the default backup_paths list, you can define it per-host here.
# backup_exclude='["/home/backup", "/var/run"]' syntax
# Also can set backup "increments" and "keep", example increments=30 keep=1y
myserverwithsomebackups.example.com gpg_passphrase=FIXME2 gpg_keyid=FIXME
vmserver.example.com gpg_passphrase=FIXME gpg_keyid=FIXME
