---
- hosts: backup_primary
  become: yes
  roles:
    - backup_server

- hosts: backup_secondary
  become: yes
  roles:
    - backup_secondary

- hosts: backup_clients
  become: yes
  roles:
    - backup_client

- hosts: localhost
  become: yes
  roles:
    - local
